/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'carousel-slides': CarouselSlide;
    gallery: Gallery;
    articles: Article;
    events: Event;
    books: Book;
    members: Member;
    'book-requests': BookRequest;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'carousel-slides': CarouselSlidesSelect<false> | CarouselSlidesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'book-requests': BookRequestsSelect<false> | BookRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('mr' | 'en' | 'hi') | ('mr' | 'en' | 'hi')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'mr' | 'en' | 'hi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS administrators and their roles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Role determines what this user can create, edit, and delete. Enforced server-side.
   */
  role: 'super-admin' | 'editor' | 'librarian' | 'membership-manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All images, videos, and documents used across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and search engines. Required for images.
   */
  alt?: string | null;
  /**
   * Optional short caption shown below the image.
   */
  caption?: string | null;
  /**
   * Internal description for organizing media.
   */
  description?: string | null;
  /**
   * Tag media to make it easier to find and reuse.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage the main banner/carousel on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel-slides".
 */
export interface CarouselSlide {
  id: number;
  /**
   * Main heading displayed on the slide
   */
  title: string;
  subtitle?: string | null;
  /**
   * Short paragraph below the title
   */
  description?: string | null;
  mediaType: 'image' | 'video';
  /**
   * Displayed as background or right-panel image
   */
  image?: (number | null) | Media;
  /**
   * Uploaded video file (MP4/WebM)
   */
  videoFile?: (number | null) | Media;
  /**
   * YouTube or Vimeo URL (used if no file uploaded)
   */
  videoURL?: string | null;
  buttonLabel?: string | null;
  buttonURL?: string | null;
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Lower numbers display first
   */
  order?: number | null;
  isActive?: boolean | null;
  /**
   * Leave empty to show immediately
   */
  startDate?: string | null;
  /**
   * Leave empty to show indefinitely
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photo albums for events, dignitaries, and library activities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Displayed as the album thumbnail in the gallery grid
   */
  coverImage: number | Media;
  /**
   * Add photos to this album. Use the media library to upload multiple images at once.
   */
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  eventDate?: string | null;
  category?: ('dignitaries' | 'events' | 'visits' | 'exhibitions' | 'stacks' | 'other') | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Library news, blog posts, announcements
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used in the URL: /news/[slug]
   */
  slug?: string | null;
  /**
   * Short summary shown in article lists and search results
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  category?: ('announcement' | 'news' | 'blog' | 'notice') | null;
  publishDate?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to article title if left empty
     */
    title?: string | null;
    /**
     * Shown in search engine results. 150–160 characters ideal.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Library events, programs, and lectures
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * Link to a gallery album for this event
   */
  gallery?: (number | null) | Gallery;
  startDate: string;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  location?: string | null;
  registrationURL?: string | null;
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Sahitya Niketan book catalogue — 39,953+ volumes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  /**
   * Book title as it appears on the cover
   */
  title: string;
  author: string;
  publisher?: string | null;
  publicationYear?: number | null;
  isbn?: string | null;
  language: 'mr' | 'hi' | 'en' | 'sa' | 'other';
  category?:
    | (
        | 'कादंबरी'
        | 'कविता'
        | 'नाटक'
        | 'चरित्र'
        | 'इतिहास'
        | 'तत्त्वज्ञान'
        | 'विज्ञान'
        | 'बालसाहित्य'
        | 'संदर्भ'
        | 'हस्तलिखित'
        | 'धर्मशास्त्र'
        | 'समाजशास्त्र'
        | 'अर्थशास्त्र'
        | 'स्पर्धा परीक्षा'
        | 'english_literature'
        | 'other'
      )
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  availability: 'available' | 'issued' | 'reference_only';
  shelfReference?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Library membership applications and records
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  membershipType: 'standard' | 'student' | 'senior' | 'lifetime';
  status: 'pending' | 'active' | 'expired' | 'suspended';
  membershipStart?: string | null;
  membershipEnd?: string | null;
  /**
   * Internal notes — not visible to members
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Book borrowing requests and circulation queue
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-requests".
 */
export interface BookRequest {
  id: number;
  book: number | Book;
  requesterName: string;
  requesterContact?: string | null;
  status: 'pending' | 'approved' | 'issued' | 'returned' | 'rejected';
  requestDate?: string | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Custom pages built with approved content blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path: /[slug]. Use lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Build the page by adding and reordering sections. Only approved section types are available.
   */
  sections?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            description?: string | null;
            image?: (number | null) | Media;
            primaryButtonLabel?: string | null;
            primaryButtonURL?: string | null;
            secondaryButtonLabel?: string | null;
            secondaryButtonURL?: string | null;
            alignment?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('standard' | 'wide' | 'narrow') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            imagePosition?: ('left' | 'right') | null;
            buttonLabel?: string | null;
            buttonURL?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            gallery: number | Gallery;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            heading?: string | null;
            caption?: string | null;
            videoType?: ('url' | 'file') | null;
            videoURL?: string | null;
            videoFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  linkLabel?: string | null;
                  linkURL?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            heading?: string | null;
            eventFilter?: ('upcoming' | 'completed' | 'all') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsBlock';
          }
        | {
            heading?: string | null;
            /**
             * Select specific books, or leave empty to show featured books
             */
            books?: (number | Book)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booksBlock';
          }
        | {
            heading?: string | null;
            events?:
              | {
                  year: string;
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            quote: string;
            attribution?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButtonLabel?: string | null;
            primaryButtonURL?: string | null;
            secondaryButtonLabel?: string | null;
            secondaryButtonURL?: string | null;
            style?: ('default' | 'highlighted' | 'subtle') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'carousel-slides';
        value: number | CarouselSlide;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'book-requests';
        value: number | BookRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel-slides_select".
 */
export interface CarouselSlidesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  mediaType?: T;
  image?: T;
  videoFile?: T;
  videoURL?: T;
  buttonLabel?: T;
  buttonURL?: T;
  alignment?: T;
  order?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coverImage?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        order?: T;
        id?: T;
      };
  eventDate?: T;
  category?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  publishDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  featuredImage?: T;
  gallery?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  registrationURL?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  publisher?: T;
  publicationYear?: T;
  isbn?: T;
  language?: T;
  category?: T;
  description?: T;
  coverImage?: T;
  availability?: T;
  shelfReference?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  membershipType?: T;
  status?: T;
  membershipStart?: T;
  membershipEnd?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-requests_select".
 */
export interface BookRequestsSelect<T extends boolean = true> {
  book?: T;
  requesterName?: T;
  requesterContact?: T;
  status?: T;
  requestDate?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              image?: T;
              primaryButtonLabel?: T;
              primaryButtonURL?: T;
              secondaryButtonLabel?: T;
              secondaryButtonURL?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              heading?: T;
              content?: T;
              imagePosition?: T;
              buttonLabel?: T;
              buttonURL?: T;
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              heading?: T;
              gallery?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              caption?: T;
              videoType?: T;
              videoURL?: T;
              videoFile?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    linkLabel?: T;
                    linkURL?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        eventsBlock?:
          | T
          | {
              heading?: T;
              eventFilter?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        booksBlock?:
          | T
          | {
              heading?: T;
              books?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              events?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryButtonURL?: T;
              secondaryButtonLabel?: T;
              secondaryButtonURL?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global website configuration — logo, contact, SEO, social media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Main site logo
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon (32×32 or 64×64 PNG/ICO)
   */
  favicon?: (number | null) | Media;
  libraryName: string;
  libraryTagline?: string | null;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    hoursWeekday?: string | null;
    hoursWeekend?: string | null;
    googleMapsURL?: string | null;
    whatsapp?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    twitter?: string | null;
  };
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Short text shown in the footer
   */
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyrightText?: string | null;
  /**
   * Displayed in the hero section stats bar
   */
  stats?: {
    totalBooks?: string | null;
    totalMembers?: string | null;
    yearEstablished?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage main navigation and footer links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Drag to reorder. Changes are live after saving.
   */
  mainNav?:
    | {
        label: string;
        url: string;
        isVisible?: boolean | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links shown in the footer
   */
  footerNav?:
    | {
        label: string;
        url: string;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Grouped link columns shown in the footer
   */
  footerColumns?:
    | {
        columnTitle: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  libraryName?: T;
  libraryTagline?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        hoursWeekday?: T;
        hoursWeekend?: T;
        googleMapsURL?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        twitter?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  footerText?: T;
  copyrightText?: T;
  stats?:
    | T
    | {
        totalBooks?: T;
        totalMembers?: T;
        yearEstablished?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        isVisible?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        label?: T;
        url?: T;
        isVisible?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        columnTitle?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


// @ts-ignore
declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}